
import { BookStructure, Language } from './types';

// Updated Skeleton to match the new item counts (specifically Cap 21)
const BOOK_SKELETON = [
    { id: "intro", subchapters: ["1.0", "1.1", "1.2", "1.3"] },
    { id: "cap2", subchapters: ["2.0", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7"] },
    { id: "cap3", subchapters: ["3.0", "3.1", "3.2", "3.3", "3.4", "3.5", "3.6", "3.7"] },
    { id: "cap4", subchapters: ["4.0", "4.1", "4.2", "4.3", "4.4", "4.5", "4.6", "4.7"] },
    { id: "cap5", subchapters: ["5.0", "5.1", "5.2", "5.3", "5.4", "5.5", "5.6", "5.7"] },
    { id: "cap6", subchapters: ["6.0", "6.1", "6.2", "6.3", "6.4", "6.5", "6.6", "6.7"] },
    { id: "cap7", subchapters: ["7.0", "7.1", "7.2", "7.3", "7.4", "7.5", "7.6", "7.7"] },
    { id: "cap8", subchapters: ["8.0", "8.1", "8.2", "8.3", "8.4", "8.5", "8.6", "8.7"] },
    { id: "cap9", subchapters: ["9.0", "9.1", "9.2", "9.3", "9.4", "9.5", "9.6", "9.7"] },
    { id: "cap10", subchapters: ["10.0", "10.1", "10.2", "10.3", "10.4", "10.5", "10.6", "10.7"] },
    { id: "cap11", subchapters: ["11.0", "11.1", "11.2", "11.3", "11.4", "11.5", "11.6", "11.7"] },
    { id: "cap12", subchapters: ["12.0", "12.1", "12.2", "12.3", "12.4", "12.5", "12.6", "12.7"] },
    { id: "cap13", subchapters: ["13.0", "13.1", "13.2", "13.3", "13.4", "13.5", "13.6", "13.7"] },
    { id: "cap14", subchapters: ["14.0", "14.1", "14.2", "14.3", "14.4", "14.5"] },
    { id: "cap15", subchapters: ["15.0", "15.1", "15.2", "15.3", "15.4", "15.5", "15.6", "15.7"] },
    { id: "cap16", subchapters: ["16.0", "16.1", "16.2", "16.3", "16.4", "16.5", "16.6", "16.7"] },
    { id: "cap17", subchapters: ["17.0", "17.1", "17.2", "17.3", "17.4", "17.5", "17.6", "17.7"] },
    { id: "cap18", subchapters: ["18.0", "18.1", "18.2", "18.3", "18.4", "18.5", "18.6", "18.7"] },
    { id: "cap19", subchapters: ["19.0", "19.1", "19.2", "19.3", "19.4", "19.5", "19.6", "19.7"] },
    { id: "cap20", subchapters: ["20.0", "20.1", "20.2", "20.3", "20.4", "20.5", "20.6", "20.7"] },
    { id: "cap21", subchapters: ["21.1", "21.2", "21.3", "21.4", "21.5", "21.6", "21.7"] }
];

const LOCALE_DATA: Record<Language, any> = {
    pt: {
        title: "Portais da Consciência",
        subtitle: "Além dos Limites da Percepção para a Transformação da Consciência",
        chapters: {
            "intro": "Introdução: O Chamado",
            "cap2": "Cap 2: Hipnose Ericksoniana e PNL",
            "cap3": "Cap 3: A Natureza da Realidade Quântica",
            "cap4": "Cap 4: Portais Psicodélicos",
            "cap5": "Cap 5: Consciência Cósmica",
            "cap6": "Cap 6: Arte das Metáforas Terapêuticas",
            "cap7": "Cap 7: Ensinamentos Sagrados",
            "cap8": "Cap 8: Jornada do Autoconhecimento",
            "cap9": "Cap 9: Poder da Mente Subconsciente",
            "cap10": "Cap 10: Além do Tempo Linear",
            "cap11": "Cap 11: As Chaves para a Iluminação",
            "cap12": "Cap 12: Conexão Mente e Universo",
            "cap13": "Cap 13: A Ciência da Transformação",
            "cap14": "Cap 14: Caminho da Autotransformação",
            "cap15": "Cap 15: Arte da Hipnose e PNL (Ferramentas)",
            "cap16": "Cap 16: Desvendando a Realidade Quântica",
            "cap17": "Cap 17: A Transcendência Espiritual",
            "cap18": "Cap 18: Além do Ego",
            "cap19": "Cap 19: Ciência da Consciência Quântica",
            "cap20": "Cap 20: A Unidade nos Portais",
            "cap21": "Cap 21: Considerações Finais"
        },
        subchapters: {
            "1.0": ["1.0 O Chamado para a Exploração da Consciência", "Introdução aos mistérios."],
            "1.1": ["1.1 A Convergência da Ciência e Espiritualidade", "Unindo os dois mundos."],
            "1.2": ["1.2 A Mente Quântica e os Mistérios da Percepção", "Redefinindo a realidade."],
            "1.3": ["1.3 Desvendando a Jornada Rumo à Transformação Interior", "O caminho do despertar."],

            "2.0": ["2.0 Hipnose Ericksoniana e PNL: Portais para o Inconsciente", "Acesso profundo."],
            "2.1": ["2.1 Os Fundamentos da Hipnose Ericksoniana de Milton Erickson", "A base terapêutica."],
            "2.2": ["2.2 Técnicas Avançadas de Hipnose e PNL de Robert Dilts", "Evolução sistêmica."],
            "2.3": ["2.3 A Programação Neurolinguística e o Acesso ao Potencial Interior", "Desbloqueio."],
            "2.4": ["2.4 Metáforas Terapêuticas para a Transformação", "Cura através de histórias."],
            "2.5": ["2.5 A Integração das Abordagens para o Crescimento Pessoal", "Sinergia."],
            "2.6": ["2.6 Desbloqueando Limitações e Crenças Inconscientes", "Ressignificação."],
            "2.7": ["2.7 O Poder da Comunicação Não-Verbal e Linguagem Hipnótica", "Influência sutil."],

            "3.0": ["3.0 A Natureza da Realidade Quântica", "Além do Tempo e Espaço."],
            "3.1": ["3.1 O Princípio da Incerteza e a Realidade Observador-Observado", "O efeito do olhar."],
            "3.2": ["3.2 A Interconexão Quântica e a Unidade da Existência", "Entrelaçamento."],
            "3.3": ["3.3 A Consciência e o Papel na Criação da Realidade", "Mente criadora."],
            "3.4": ["3.4 A Física Quântica e a Exploração da Natureza da Realidade", "Fundamentos."],
            "3.5": ["3.5 As Implicações Filosóficas e Espirituais da Mecânica Quântica", "Filosofia."],
            "3.6": ["3.6 Conexões Entre Mente, Matéria e Universo", "A teia cósmica."],
            "3.7": ["3.7 A Busca pela Consciência Cósmica e Transcendência", "O salto final."],

            "4.0": ["4.0 Portais Psicodélicos: DMT, Psilocibina e Ayahuasca", "Substâncias de poder."],
            "4.1": ["4.1 As Experiências Psicodélicas Além dos Sentidos Comuns", "Fenomenologia."],
            "4.2": ["4.2 Viagens da Consciência e Revelações Profundas", "Insights."],
            "4.3": ["4.3 A Integração das Experiências Psicodélicas na Vida Cotidiana", "Pós-jornada."],
            "4.4": ["4.4 A Ciência das Substâncias Psicoativas e Seus Efeitos", "Neuroquímica."],
            "4.5": ["4.5 Os Aspectos Terapêuticos e Espirituais das Jornadas", "Cura."],
            "4.6": ["4.6 A Relação Entre os Psicodélicos e a Percepção Quântica", "Visão ampliada."],
            "4.7": ["4.7 Responsabilidade e Orientações para Exploração Consciente", "Segurança."],

            "5.0": ["5.0 Explorando a Consciência Cósmica", "A Unidade com o Universo."],
            "5.1": ["5.1 A Sintonia com a Consciência Universal", "Alinhamento."],
            "5.2": ["5.2 A Dimensão Quântica do Tempo e Espaço", "Novas dimensões."],
            "5.3": ["5.3 A Mente e o Universo como Um Só", "Não-dualidade."],
            "5.4": ["5.4 A Conexão entre Mente e Matéria no Tecido do Universo", "Interação."],
            "5.5": ["5.5 A Consciência Cósmica e a Busca Pela Unidade", "O retorno."],
            "5.6": ["5.6 A Expansão da Percepção e a Realização da Unidade", "Iluminação."],
            "5.7": ["5.7 O Caminho da Iluminação e a Integração Cósmica", "Vivência."],

            "6.0": ["6.0 Despertando a Sabedoria Interior", "A Arte das Metáforas."],
            "6.1": ["6.1 A Magia da Comunicação por Meio de Metáforas", "Linguagem da alma."],
            "6.2": ["6.2 A Transformação Através de Histórias Curativas", "Narrativa."],
            "6.3": ["6.3 A Simbologia Arquetípica e o Autoconhecimento", "Arquétipos."],
            "6.4": ["6.4 Utilizando Metáforas na Hipnose e PNL", "Técnica aplicada."],
            "6.5": ["6.5 Ampliando a Criatividade e Resiliência Mental", "Flexibilidade."],
            "6.6": ["6.6 As Metáforas na Prática Clínica e Terapêutica", "Consultório."],
            "6.7": ["6.7 Integração da Metáfora na Vida Cotidiana e Relações", "Dia a dia."],

            "7.0": ["7.0 Ensinamentos Sagrados", "Revelações Interiores."],
            "7.1": ["7.1 Compreendendo Palavras Sagradas de Meishu-Sama", "Johrei e Verdade."],
            "7.2": ["7.2 A Jornada Espiritual através de Mensagens de Jesus Cristo", "Amor Crístico."],
            "7.3": ["7.3 Harmonizando Saberes Milenares para a Evolução", "Síntese."],
            "7.4": ["7.4 A Universalidade dos Ensinamentos Espirituais", "Essência comum."],
            "7.5": ["7.5 A Relevância dos Ensinamentos Sagrados na Era Quântica", "Atualidade."],
            "7.6": ["7.6 Explorando a Sabedoria Interior por Meio dos Ensinamentos", "Gnose."],
            "7.7": ["7.7 Práticas Espirituais para o Despertar da Consciência", "Ação."],

            "8.0": ["8.0 A Jornada do Autoconhecimento", "Conectando-se com a Essência."],
            "8.1": ["8.1 Explorando o Eu Profundo e a Autotransformação", "Mergulho interno."],
            "8.2": ["8.2 Em Busca da Harmonia e Equilibrio Interno", "Paz interior."],
            "8.3": ["8.3 Despertando a Consciência para o Potencial Humano", "Capacidade."],
            "8.4": ["8.4 Ferramentas de Autoconhecimento e Autodesenvolvimento", "Práticas."],
            "8.5": ["8.5 A Jornada de Cura e Criação da Versão Autêntica", "Autenticidade."],
            "8.6": ["8.6 Integrando a Mente Quântica ao Autoconhecimento", "Gestão de Si."],
            "8.7": ["8.7 Práticas Diárias para a Expansão da Consciência", "Rotina."],

            "9.0": ["9.0 O Poder da Mente Subconsciente", "Manifestação."],
            "9.1": ["9.1 A Ciência da Manifestação e a Lei da Atração", "Magnetismo."],
            "9.2": ["9.2 A Transformação Pela Ressignificação das Crenças", "Mudança."],
            "9.3": ["9.3 O Potencial da Mente Quântica para Alcançar Objetivos", "Foco."],
            "9.4": ["9.4 O Poder do Subconsciente e a Realização de Metas", "Conquista."],
            "9.5": ["9.5 A Mente Quântica e a Cocriação da Realidade", "Criador."],
            "9.6": ["9.6 Práticas para o Fortalecimento da Mente Subconsciente", "Treino."],
            "9.7": ["9.7 Integrando a Consciência Quântica na Autotransformação", "Fusão."],

            "10.0": ["10.0 Além do Tempo Linear", "A Eternidade do Agora."],
            "10.1": ["10.1 A Conexão com o Eterno Presente", "Power of Now."],
            "10.2": ["10.2 A Dimensão Quântica do Tempo e suas Implicações", "Não-linearidade."],
            "10.3": ["10.3 Vivendo com Mindfulness e Plenitude no Agora", "Atenção Plena."],
            "10.4": ["10.4 A Mente Quântica e a Percepção do Tempo", "Subjetividade."],
            "10.5": ["10.5 Liberando Traumas do Passado e Preocupações do Futuro", "Cura temporal."],
            "10.6": ["10.6 A Expansão da Consciência no Fluxo do Agora", "Flow."],
            "10.7": ["10.7 O Presente como Fonte de Transformação e Criação", "Ponto Zero."],

            "11.0": ["11.0 As Chaves para a Iluminação", "Amor e Compaixão."],
            "11.1": ["11.1 O Amor Incondicional como Força Transformadora", "Agape."],
            "11.2": ["11.2 A Compaixão e a Unidade com a Humanidade", "Empatia."],
            "11.3": ["11.3 O Caminho da Iluminação Pela Transformação Interior", "Luz."],
            "11.4": ["11.4 Práticas Espirituais de Amor e Compaixão", "Metta."],
            "11.5": ["11.5 A Conexão entre Amor, Compaixão e Consciência Quântica", "Frequência."],
            "11.6": ["11.6 O Cultivo da Auto Compaixão e Aceitação", "Amor próprio."],
            "11.7": ["11.7 A Jornada de Iluminação e a Transformação do Ser", "Realização."],

            "12.0": ["12.0 A Conexão Entre a Mente e o Universo", "Explorando a Consciência."],
            "12.1": ["12.1 A Sintonia com a Consciência Universal", "Ressonância."],
            "12.2": ["12.2 A Intuição e a Percepção Além dos Cinco Sentidos", "Sexto sentido."],
            "12.3": ["12.3 A Coerência da Mente Quântica e a Sabedoria Cósmica", "Ordem."],
            "12.4": ["12.4 A Consciência Cósmica e a Exploração do Infinito", "Sem limites."],
            "12.5": ["12.5 A Conexão com a Inteligência Universal e o Propósito", "Dharma."],
            "12.6": ["12.6 A Consciência Cósmica na Arte, Ciência e Espiritualidade", "Expressão."],
            "12.7": ["12.7 Vivendo em Harmonia com a Ordem Universal", "Tao."],

            "13.0": ["13.0 A Ciência da Transformação", "DMT e Psilocibina."],
            "13.1": ["13.1 A Neurociência por Trás das Experiências Psicodélicas", "Cérebro."],
            "13.2": ["13.2 O Potencial Terapêutico das Substâncias Psicoativas", "Medicina."],
            "13.3": ["13.3 A Expansão da Consciência e a Reconexão Interior", "Self."],
            "13.4": ["13.4 A Ciência do 'Eu' e da Mente na Experiência Psicodélica", "Ego dissolution."],
            "13.5": ["13.5 A Transformação Cognitiva e Emocional Através das Substâncias", "Neuroplasticidade."],
            "13.6": ["13.6 Integrando Experiências Psicodélicas na Vida Cotidiana", "Aterrissagem."],
            "13.7": ["13.7 Responsabilidade e Orientações para a Jornada Psicodélica", "Set and Setting."],

            "14.0": ["14.0 O Caminho da Autotransformação", "Espiritualidade."],
            "14.1": ["14.1 Compreendendo as Palavras Sagradas de Meishu-Sama", "Luz Divina."],
            "14.2": ["14.2 As Mensagens de Jesus Cristo e sua Interpretação por Kyoshu-Sama", "Messianismo."],
            "14.3": ["14.3 Harmonizando Conhecimentos Espirituais para a Evolução", "Integração."],
            "14.4": ["14.4 Ensinamentos e Práticas Espirituais para a Autotransformação", "Prática."],
            "14.5": ["14.5 A Busca pela Iluminação e a Unificação das Religiões", "Unidade."],

            "15.0": ["15.0 A Arte da Hipnose e PNL", "Ferramentas de Autoconhecimento."],
            "15.1": ["15.1 A Hipnose Ericksoniana de Milton Erickson", "O Pai da Hipnose."],
            "15.2": ["15.2 Técnicas Avançadas de Hipnose e PNL de Robert Dilts", "Modelagem."],
            "15.3": ["15.3 Utilizando Metáforas na Hipnose e PNL", "Linguagem Indireta."],
            "15.4": ["15.4 Ampliando a Criatividade e Resiliência Mental", "Recursos."],
            "15.5": ["15.5 A Comunicação Não-Verbal e Linguagem Hipnótica", "Sinais."],
            "15.6": ["15.6 Hipnose e PNL na Terapia e Transformação", "Clínica."],
            "15.7": ["15.7 Aplicações Práticas para a Autodescoberta e Crescimento", "Exercícios."],

            "16.0": ["16.0 Desvendando a Realidade Quântica", "Além dos Limites."],
            "16.1": ["16.1 A Natureza Quântica do Universo e da Mente", "Fundamentos."],
            "16.2": ["16.2 O Papel do Observador e a Criação da Realidade", "Colapso da função."],
            "16.3": ["16.3 Explorando a Mente e a Consciência Além dos Paradigmas", "Novos modelos."],
            "16.4": ["16.4 O Entrelaçamento Quântico e a Interconexão do Tudo", "Emaranhamento."],
            "16.5": ["16.5 A Não-Localidade da Consciência e dos Fenômenos", "Onipresença."],
            "16.6": ["16.6 A Realidade Multidimensional e o Campo Quântico", "Dimensões."],
            "16.7": ["16.7 A Ampliação da Percepção e Novos Horizontes", "Evolução."],

            "17.0": ["17.0 A Transcendência Espiritual", "Elevando a Consciência."],
            "17.1": ["17.1 A Busca pela Conexão Espiritual e Transcendência", "O Sagrado."],
            "17.2": ["17.2 A Unidade com o Divino e a Essência Espiritual", "Fusão."],
            "17.3": ["17.3 A Expansão da Consciência em Níveis Superiores", "Ascensão."],
            "17.4": ["17.4 O Caminho da Iluminação e a Elevação Vibracional", "Energia."],
            "17.5": ["17.5 A Consciência Cósmica e a Unificação Espiritual", "Todo."],
            "17.6": ["17.6 Práticas para a Transcendência e Iluminação Interior", "Sadhana."],
            "17.7": ["17.7 O Propósito de Vida e a Contribuição para a Humanidade", "Missão."],

            "18.0": ["18.0 Além do Ego", "Reconexão com o Superior."],
            "18.1": ["18.1 A Natureza do Ego e seus Desafios na Jornada Interior", "A máscara."],
            "18.2": ["18.2 O Caminho da Desidentificação e Liberação do Ego", "Soltar."],
            "18.3": ["18.3 A Consciência Superior e o Eu Autêntico", "Self."],
            "18.4": ["18.4 O Despertar da Consciência Testemunha e a Presença Eu Sou", "Observador."],
            "18.5": ["18.5 A Conexão com o Eu Divino e a Unidade Essencial", "Centelha."],
            "18.6": ["18.6 A Transcendência do Ego e a Experiência da Unidade", "Dissolução."],
            "18.7": ["18.7 Integrando a Consciência Superior na Vida Diária", "Viver."],

            "19.0": ["19.0 A Ciência da Consciência Quântica", "Pesquisas e Avanços."],
            "19.1": ["19.1 As Fronteiras da Neurociência e a Consciência", "Cérebro-Mente."],
            "19.2": ["19.2 A Ressonância Magnética e Estudos da Mente", "Imagens."],
            "19.3": ["19.3 A Epigenética e a Influência do Pensamento na Saúde", "Biologia."],
            "19.4": ["19.4 Pesquisas Sobre a Mente Quântica e Estados Ampliados", "Estudos."],
            "19.5": ["19.5 A Consciência e a Expansão da Inteligência Humana", "Evolução."],
            "19.6": ["19.6 As Perspectivas Futuras da Ciência da Consciência", "Futuro."],
            "19.7": ["19.7 A Interconexão Entre Ciência e Espiritualidade", "Verdade."],

            "20.0": ["20.0 A Unidade nos Portais da Transformação", "Sistêmica."],
            "20.1": ["20.1 Herança de Sabedoria Familiar: Tecendo Relações", "Ancestralidade."],
            "20.2": ["20.2 A Dança da Comunicação: Metáforas e Histórias", "Diálogo."],
            "20.3": ["20.3 A Alma da Ciência e Espiritualidade: Um Diálogo Sagrado", "Encontro."],
            "20.4": ["20.4 O Ritual da Transformação: Uma Jornada Além do Tempo", "Rito."],
            "20.5": ["20.5 Em Busca da Essência: O Eu Autêntico e o Propósito", "Verdade."],
            "20.6": ["20.6 A Unidade Cósmica: Além do Ego e da Mente", "Cosmos."],
            "20.7": ["20.7 O Legado de Virginia Satir: Um Farol para o Futuro", "Família."],

            "21.1": ["21.1 Recapitulando a Exploração dos Portais da Consciência", "Síntese."],
            "21.2": ["21.2 O Chamado para o Autoconhecimento e a Autotransformação", "Ação."],
            "21.3": ["21.3 Uma Mensagem de Gratidão aos Leitores e Colaboradores", "Gratidão."],
            "21.4": ["21.4 A Percepção Além das Palavras Sagradas e Ensinamentos", "Essência."],
            "21.5": ["21.5 Um Convite à Exploração dos Mistérios do Ser", "Convite."],
            "21.6": ["21.6 A Sabedoria Quântica e o Potencial de Transformação", "Potencial."],
            "21.7": ["21.7 O Caminho Infinito da Consciência e a Evolução Contínua", "Eternidade."]
        }
    },
    en: {
        title: "Portals of Consciousness",
        subtitle: "Beyond the Limits of Perception for Consciousness Transformation",
        chapters: {
            "intro": "Introduction: The Call",
            "cap2": "Ch 2: Ericksonian Hypnosis & NLP",
            "cap3": "Ch 3: The Nature of Quantum Reality",
            "cap4": "Ch 4: Psychedelic Portals",
            "cap5": "Ch 5: Cosmic Consciousness",
            "cap6": "Ch 6: Art of Therapeutic Metaphors",
            "cap7": "Ch 7: Sacred Teachings",
            "cap8": "Ch 8: Journey of Self-Knowledge",
            "cap9": "Ch 9: Power of Subconscious Mind",
            "cap10": "Ch 10: Beyond Linear Time",
            "cap11": "Ch 11: Keys to Enlightenment",
            "cap12": "Ch 12: Mind and Universe Connection",
            "cap13": "Ch 13: The Science of Transformation",
            "cap14": "Ch 14: Path of Self-Transformation",
            "cap15": "Ch 15: Art of Hypnosis & NLP (Tools)",
            "cap16": "Ch 16: Unveiling Quantum Reality",
            "cap17": "Ch 17: Spiritual Transcendence",
            "cap18": "Ch 18: Beyond the Ego",
            "cap19": "Ch 19: Quantum Consciousness Science",
            "cap20": "Ch 20: Unity in the Portals",
            "cap21": "Ch 21: Final Considerations"
        },
        subchapters: {
            "1.0": ["1.0 The Call for Consciousness Exploration", "Introduction to mysteries."],
            "1.1": ["1.1 The Convergence of Science and Spirituality", "Uniting two worlds."],
            "1.2": ["1.2 The Quantum Mind and Mysteries of Perception", "Redefining reality."],
            "1.3": ["1.3 Unveiling the Journey Toward Inner Transformation", "The path of awakening."],

            "2.0": ["2.0 Ericksonian Hypnosis and NLP: Portals to the Unconscious", "Deep access."],
            "2.1": ["2.1 Fundamentals of Milton Erickson's Hypnosis", "Therapeutic basis."],
            "2.2": ["2.2 Advanced Hypnosis and NLP Techniques by Robert Dilts", "Systemic evolution."],
            "2.3": ["2.3 Neuro-Linguistic Programming and Accessing Inner Potential", "Unlocking."],
            "2.4": ["2.4 Therapeutic Metaphors for Transformation", "Healing through stories."],
            "2.5": ["2.5 Integrating Approaches for Personal Growth", "Synergy."],
            "2.6": ["2.6 Unlocking Limitations and Unconscious Beliefs", "Reframing."],
            "2.7": ["2.7 The Power of Non-Verbal Communication and Hypnotic Language", "Subtle influence."],

            "3.0": ["3.0 The Nature of Quantum Reality", "Beyond Time and Space."],
            "3.1": ["3.1 Uncertainty Principle and Observer-Observed Reality", "The gaze effect."],
            "3.2": ["3.2 Quantum Interconnection and Unity of Existence", "Entanglement."],
            "3.3": ["3.3 Consciousness and its Role in Creating Reality", "Creative mind."],
            "3.4": ["3.4 Quantum Physics and Exploration of Reality's Nature", "Fundamentals."],
            "3.5": ["3.5 Philosophical and Spiritual Implications of Quantum Mechanics", "Philosophy."],
            "3.6": ["3.6 Connections Between Mind, Matter, and Universe", "Cosmic web."],
            "3.7": ["3.7 The Quest for Cosmic Consciousness and Transcendence", "The final leap."],

            "4.0": ["4.0 Psychedelic Portals: DMT, Psilocybin and Ayahuasca", "Power substances."],
            "4.1": ["4.1 Psychedelic Experiences Beyond Common Senses", "Phenomenology."],
            "4.2": ["4.2 Consciousness Journeys and Profound Revelations", "Insights."],
            "4.3": ["4.3 Integrating Psychedelic Experiences into Daily Life", "Post-journey."],
            "4.4": ["4.4 Science of Psychoactive Substances and Mind Effects", "Neurochemistry."],
            "4.5": ["4.5 Therapeutic and Spiritual Aspects of Journeys", "Healing."],
            "4.6": ["4.6 Relationship Between Psychedelics and Quantum Perception", "Expanded view."],
            "4.7": ["4.7 Responsibility and Guidelines for Conscious Exploration", "Safety."],

            "5.0": ["5.0 Exploring Cosmic Consciousness", "Unity with the Universe."],
            "5.1": ["5.1 Tuning into Universal Consciousness", "Alignment."],
            "5.2": ["5.2 The Quantum Dimension of Time and Space", "New dimensions."],
            "5.3": ["5.3 Mind and Universe as One", "Non-duality."],
            "5.4": ["5.4 Connection between Mind and Matter in Universe Fabric", "Interaction."],
            "5.5": ["5.5 Cosmic Consciousness and the Quest for Unity", "The return."],
            "5.6": ["5.6 Expansion of Perception and Realization of Unity", "Enlightenment."],
            "5.7": ["5.7 Path of Enlightenment and Cosmic Integration", "Lived experience."],

            "6.0": ["6.0 Awakening Inner Wisdom", "The Art of Metaphors."],
            "6.1": ["6.1 The Magic of Communication Through Metaphors", "Soul language."],
            "6.2": ["6.2 Transformation Through Healing Stories", "Narrative."],
            "6.3": ["6.3 Archetypal Symbology and Self-Knowledge", "Archetypes."],
            "6.4": ["6.4 Using Metaphors in Hypnosis and NLP", "Applied technique."],
            "6.5": ["6.5 Expanding Creativity and Mental Resilience", "Flexibility."],
            "6.6": ["6.6 Metaphors in Clinical and Therapeutic Practice", "Office."],
            "6.7": ["6.7 Integrating Metaphor into Daily Life and Relations", "Day to day."],

            "7.0": ["7.0 Sacred Teachings", "Inner Revelations."],
            "7.1": ["7.1 Understanding Sacred Words of Meishu-Sama", "Johrei and Truth."],
            "7.2": ["7.2 Spiritual Journey through Messages of Jesus Christ", "Christic Love."],
            "7.3": ["7.3 Harmonizing Ancient Wisdom for Evolution", "Synthesis."],
            "7.4": ["7.4 Universality of Spiritual Teachings", "Common essence."],
            "7.5": ["7.5 Relevance of Sacred Teachings in Quantum Era", "Current relevance."],
            "7.6": ["7.6 Exploring Inner Wisdom Through Teachings", "Gnosis."],
            "7.7": ["7.7 Spiritual Practices for Consciousness Awakening", "Action."],

            "8.0": ["8.0 Journey of Self-Knowledge", "Connecting with Essence."],
            "8.1": ["8.1 Exploring Deep Self and Self-Transformation", "Inner dive."],
            "8.2": ["8.2 In Search of Harmony and Inner Balance", "Inner peace."],
            "8.3": ["8.3 Awakening Consciousness to Human Potential", "Capacity."],
            "8.4": ["8.4 Tools for Self-Knowledge and Self-Development", "Practices."],
            "8.5": ["8.5 Healing Journey and Creating Authentic Self", "Authenticity."],
            "8.6": ["8.6 Integrating Quantum Mind to Self-Knowledge", "Self-Management."],
            "8.7": ["8.7 Daily Practices for Consciousness Expansion", "Routine."],

            "9.0": ["9.0 Power of Subconscious Mind", "Manifestation."],
            "9.1": ["9.1 Science of Manifestation and Law of Attraction", "Magnetism."],
            "9.2": ["9.2 Transformation Through Reframing Beliefs", "Change."],
            "9.3": ["9.3 Potential of Quantum Mind to Achieve Goals", "Focus."],
            "9.4": ["9.4 Power of Subconscious and Goal Realization", "Achievement."],
            "9.5": ["9.5 Quantum Mind and Co-creation of Reality", "Creator."],
            "9.6": ["9.6 Practices for Strengthening Subconscious Mind", "Training."],
            "9.7": ["9.7 Integrating Quantum Consciousness in Self-Transformation", "Fusion."],

            "10.0": ["10.0 Beyond Linear Time", "Eternity of Now."],
            "10.1": ["10.1 Connection with Eternal Present", "Power of Now."],
            "10.2": ["10.2 Quantum Dimension of Time and Implications", "Non-linearity."],
            "10.3": ["10.3 Living with Mindfulness and Fullness in Now", "Mindfulness."],
            "10.4": ["10.4 Quantum Mind and Time Perception", "Subjectivity."],
            "10.5": ["10.5 Releasing Past Trauma and Future Worries", "Temporal healing."],
            "10.6": ["10.6 Consciousness Expansion in Flow of Now", "Flow."],
            "10.7": ["10.7 The Present as Source of Transformation", "Zero Point."],

            "11.0": ["11.0 Keys to Enlightenment", "Love and Compassion."],
            "11.1": ["11.1 Unconditional Love as Transformative Force", "Agape."],
            "11.2": ["11.2 Compassion and Unity with Humanity", "Empathy."],
            "11.3": ["11.3 Path of Enlightenment Through Inner Transformation", "Light."],
            "11.4": ["11.4 Spiritual Practices of Love and Compassion", "Metta."],
            "11.5": ["11.5 Connection between Love, Compassion and Quantum Consciousness", "Frequency."],
            "11.6": ["11.6 Cultivating Self-Compassion and Acceptance", "Self-love."],
            "11.7": ["11.7 Journey of Enlightenment and Being Transformation", "Realization."],

            "12.0": ["12.0 Connection Between Mind and Universe", "Exploring Consciousness."],
            "12.1": ["12.1 Tuning into Universal Consciousness", "Resonance."],
            "12.2": ["12.2 Intuition and Perception Beyond Five Senses", "Sixth sense."],
            "12.3": ["12.3 Coherence of Quantum Mind and Cosmic Wisdom", "Order."],
            "12.4": ["12.4 Cosmic Consciousness and Infinite Exploration", "No limits."],
            "12.5": ["12.5 Connection with Universal Intelligence and Purpose", "Dharma."],
            "12.6": ["12.6 Cosmic Consciousness in Art, Science and Spirituality", "Expression."],
            "12.7": ["12.7 Living in Harmony with Universal Order", "Tao."],

            "13.0": ["13.0 The Science of Transformation", "DMT and Psilocybin."],
            "13.1": ["13.1 Neuroscience Behind Psychedelic Experiences", "Brain."],
            "13.2": ["13.2 Therapeutic Potential of Psychoactive Substances", "Medicine."],
            "13.3": ["13.3 Consciousness Expansion and Inner Reconnection", "Self."],
            "13.4": ["13.4 Science of 'Self' and Mind in Psychedelic Experience", "Ego dissolution."],
            "13.5": ["13.5 Cognitive and Emotional Transformation Through Substances", "Neuroplasticity."],
            "13.6": ["13.6 Integrating Psychedelic Experiences into Daily Life", "Landing."],
            "13.7": ["13.7 Responsibility and Guidelines for Psychedelic Journey", "Set and Setting."],

            "14.0": ["14.0 Path of Self-Transformation", "Spirituality."],
            "14.1": ["14.1 Understanding Sacred Words of Meishu-Sama", "Divine Light."],
            "14.2": ["14.2 Messages of Jesus Christ and Interpretation by Kyoshu-Sama", "Messianism."],
            "14.3": ["14.3 Harmonizing Spiritual Knowledge for Evolution", "Integration."],
            "14.4": ["14.4 Teachings and Spiritual Practices for Self-Transformation", "Practice."],
            "14.5": ["14.5 Quest for Enlightenment and Unification of Religions", "Unity."],

            "15.0": ["15.0 Art of Hypnosis and NLP", "Tools for Self-Knowledge."],
            "15.1": ["15.1 Ericksonian Hypnosis by Milton Erickson", "The Father of Hypnosis."],
            "15.2": ["15.2 Advanced Hypnosis and NLP Techniques by Robert Dilts", "Modeling."],
            "15.3": ["15.3 Using Metaphors in Hypnosis and NLP", "Indirect Language."],
            "15.4": ["15.4 Expanding Creativity and Mental Resilience", "Resources."],
            "15.5": ["15.5 Non-Verbal Communication and Hypnotic Language", "Signals."],
            "15.6": ["15.6 Hypnosis and NLP in Therapy and Transformation", "Clinic."],
            "15.7": ["15.7 Practical Applications for Self-Discovery", "Exercises."],

            "16.0": ["16.0 Unveiling Quantum Reality", "Beyond Limits."],
            "16.1": ["16.1 Quantum Nature of Universe and Mind", "Fundamentals."],
            "16.2": ["16.2 Role of Observer and Creation of Reality", "Function collapse."],
            "16.3": ["16.3 Exploring Mind and Consciousness Beyond Paradigms", "New models."],
            "16.4": ["16.4 Quantum Entanglement and Interconnection of All", "Entanglement."],
            "16.5": ["16.5 Non-Locality of Consciousness and Phenomena", "Omnipresence."],
            "16.6": ["16.6 Multidimensional Reality and Quantum Field", "Dimensions."],
            "16.7": ["16.7 Amplification of Perception and New Horizons", "Evolution."],

            "17.0": ["17.0 Spiritual Transcendence", "Elevating Consciousness."],
            "17.1": ["17.1 Quest for Spiritual Connection and Transcendence", "The Sacred."],
            "17.2": ["17.2 Unity with Divine and Spiritual Essence", "Fusion."],
            "17.3": ["17.3 Consciousness Expansion in Higher Levels", "Ascension."],
            "17.4": ["17.4 Path of Enlightenment and Vibrational Elevation", "Energy."],
            "17.5": ["17.5 Cosmic Consciousness and Spiritual Unification", "Whole."],
            "17.6": ["17.6 Practices for Transcendence and Inner Enlightenment", "Sadhana."],
            "17.7": ["17.7 Life Purpose and Contribution to Humanity", "Mission."],

            "18.0": ["18.0 Beyond Ego", "Reconnection with Higher Self."],
            "18.1": ["18.1 Nature of Ego and its Challenges in Inner Journey", "The mask."],
            "18.2": ["18.2 Path of Disidentification and Ego Release", "Letting go."],
            "18.3": ["18.3 Higher Consciousness and Authentic Self", "Self."],
            "18.4": ["18.4 Awakening Witness Consciousness and I Am Presence", "Observer."],
            "18.5": ["18.5 Connection with Divine Self and Essential Unity", "Spark."],
            "18.6": ["18.6 Transcendence of Ego and Experience of Unity", "Dissolution."],
            "18.7": ["18.7 Integrating Higher Consciousness in Daily Life", "Living."],

            "19.0": ["19.0 Science of Quantum Consciousness", "Research and Advances."],
            "19.1": ["19.1 Frontiers of Neuroscience and Consciousness", "Brain-Mind."],
            "19.2": ["19.2 MRI and Mind Studies", "Imaging."],
            "19.3": ["19.3 Epigenetics and Influence of Thought on Health", "Biology."],
            "19.4": ["19.4 Research on Quantum Mind and Expanded States", "Studies."],
            "19.5": ["19.5 Consciousness and Expansion of Human Intelligence", "Evolution."],
            "19.6": ["19.6 Future Perspectives of Consciousness Science", "Future."],
            "19.7": ["19.7 Interconnection Between Science and Spirituality", "Truth."],

            "20.0": ["20.0 Unity in Portals of Transformation", "Systemic."],
            "20.1": ["20.1 Heritage of Family Wisdom: Weaving Relations", "Ancestry."],
            "20.2": ["20.2 Dance of Communication: Metaphors and Stories", "Dialogue."],
            "20.3": ["20.3 Soul of Science and Spirituality: A Sacred Dialogue", "Meeting."],
            "20.4": ["20.4 Ritual of Transformation: A Journey Beyond Time", "Rite."],
            "20.5": ["20.5 In Search of Essence: Authentic Self and Purpose", "Truth."],
            "20.6": ["20.6 Cosmic Unity: Beyond Ego and Mind", "Cosmos."],
            "20.7": ["20.7 Legacy of Virginia Satir: A Beacon for Future", "Family."],

            "21.1": ["21.1 Recap of Exploring Portals of Consciousness", "Synthesis."],
            "21.2": ["21.2 The Call for Self-Knowledge and Self-Transformation", "Action."],
            "21.3": ["21.3 A Message of Gratitude to Readers and Collaborators", "Gratitude."],
            "21.4": ["21.4 Perception Beyond Sacred Words and Teachings", "Essence."],
            "21.5": ["21.5 An Invitation to Explore Mysteries of Being", "Invitation."],
            "21.6": ["21.6 Quantum Wisdom and Potential for Transformation", "Potential."],
            "21.7": ["21.7 Infinite Path of Consciousness and Continuous Evolution", "Eternity."]
        }
    },
    es: {
        title: "Portales de la Conciencia",
        subtitle: "Más Allá de los Límites de la Percepción para la Transformación",
        chapters: {
            "intro": "Introducción: El Llamado",
            "cap2": "Cap 2: Hipnosis Ericksoniana y PNL",
            "cap3": "Cap 3: La Naturaleza de la Realidad Cuántica",
            "cap4": "Cap 4: Portales Psicodélicos",
            "cap5": "Cap 5: Conciencia Cósmica",
            "cap6": "Cap 6: Arte de las Metáforas Terapéuticas",
            "cap7": "Cap 7: Enseñanzas Sagradas",
            "cap8": "Cap 8: Jornada del Autoconocimiento",
            "cap9": "Cap 9: Poder de la Mente Subconsciente",
            "cap10": "Cap 10: Más Allá del Tiempo Lineal",
            "cap11": "Cap 11: Las Claves para la Iluminación",
            "cap12": "Cap 12: Conexión Mente y Universo",
            "cap13": "Cap 13: La Ciencia de la Transformación",
            "cap14": "Cap 14: Camino de la Autotransformación",
            "cap15": "Cap 15: Arte de la Hipnosis y PNL (Herramientas)",
            "cap16": "Cap 16: Desvelando la Realidad Cuántica",
            "cap17": "Cap 17: La Trascendencia Espiritual",
            "cap18": "Cap 18: Más Allá del Ego",
            "cap19": "Cap 19: Ciencia de la Conciencia Cuántica",
            "cap20": "Cap 20: La Unidad en los Portales",
            "cap21": "Cap 21: Consideraciones Finales"
        },
        subchapters: {
            "1.0": ["1.0 El Llamado para la Exploración de la Conciencia", "Introducción a misterios."],
            "1.1": ["1.1 La Convergencia de Ciencia y Espiritualidad", "Uniendo dos mundos."],
            "1.2": ["1.2 La Mente Cuántica y los Misterios de la Percepción", "Redefiniendo realidad."],
            "1.3": ["1.3 Desvelando la Jornada Rumbo a la Transformación Interior", "El camino."],

            "2.0": ["2.0 Hipnosis Ericksoniana y PNL: Portales al Inconsciente", "Acceso profundo."],
            "2.1": ["2.1 Fundamentos de la Hipnosis Ericksoniana de Milton Erickson", "Base terapéutica."],
            "2.2": ["2.2 Técnicas Avanzadas de Hipnosis y PNL de Robert Dilts", "Evolución sistémica."],
            "2.3": ["2.3 Programación Neurolingüística y Acceso al Potencial Interior", "Desbloqueo."],
            "2.4": ["2.4 Metáforas Terapéuticas para la Transformación", "Cura con historias."],
            "2.5": ["2.5 Integración de Enfoques para el Crecimiento Personal", "Sinergia."],
            "2.6": ["2.6 Desbloqueando Limitaciones y Creencias Inconscientes", "Resignificación."],
            "2.7": ["2.7 El Poder de la Comunicación No Verbal y Lenguaje Hipnótico", "Influencia sutil."],

            "3.0": ["3.0 La Naturaleza de la Realidad Cuántica", "Más Allá del Tiempo y Espacio."],
            "3.1": ["3.1 El Principio de Incertidumbre y Realidad Observador-Observado", "Efecto observador."],
            "3.2": ["3.2 La Interconexión Cuántica y la Unidad de la Existencia", "Entrelazamiento."],
            "3.3": ["3.3 La Conciencia y el Papel en la Creación de la Realidad", "Mente creadora."],
            "3.4": ["3.4 La Física Cuántica y la Exploración de la Naturaleza Real", "Fundamentos."],
            "3.5": ["3.5 Las Implicaciones Filosóficas y Espirituales de la Mecánica", "Filosofía."],
            "3.6": ["3.6 Conexiones Entre Mente, Materia y Universo", "Red cósmica."],
            "3.7": ["3.7 La Búsqueda por la Conciencia Cósmica y Trascendencia", "Salto final."],

            "4.0": ["4.0 Portales Psicodélicos: DMT, Psilocibina y Ayahuasca", "Sustancias de poder."],
            "4.1": ["4.1 Las Experiencias Psicodélicas Más Allá de los Sentidos", "Fenomenología."],
            "4.2": ["4.2 Viajes de la Conciencia y Revelaciones Profundas", "Insights."],
            "4.3": ["4.3 La Integración de Experiencias Psicodélicas en la Vida", "Post-jornada."],
            "4.4": ["4.4 La Ciencia de las Sustancias Psicoactivas y sus Efectos", "Neuroquímica."],
            "4.5": ["4.5 Los Aspectos Terapéuticos y Espirituales de las Jornadas", "Cura."],
            "4.6": ["4.6 La Relación Entre Psicodélicos y Percepción Cuántica", "Visión ampliada."],
            "4.7": ["4.7 Responsabilidad y Orientaciones para Exploración Consciente", "Seguridad."],

            "5.0": ["5.0 Explorando la Conciencia Cósmica", "La Unidad con el Universo."],
            "5.1": ["5.1 La Sintonía con la Conciencia Universal", "Alineación."],
            "5.2": ["5.2 La Dimensión Cuántica del Tiempo y Espacio", "Nuevas dimensiones."],
            "5.3": ["5.3 La Mente y el Universo como Uno Solo", "No-dualidad."],
            "5.4": ["5.4 La Conexión entre Mente y Materia en Tejido del Universo", "Interacción."],
            "5.5": ["5.5 La Conciencia Cósmica y la Búsqueda Por la Unidad", "El retorno."],
            "5.6": ["5.6 La Expansión de la Percepción y Realización de la Unidad", "Iluminación."],
            "5.7": ["5.7 El Camino de la Iluminación e Integración Cósmica", "Vivencia."],

            "6.0": ["6.0 Despertando la Sabiduría Interior", "El Arte de las Metáforas."],
            "6.1": ["6.1 La Magia de la Comunicación por Medio de Metáforas", "Lenguaje del alma."],
            "6.2": ["6.2 La Transformación a Través de Historias Curativas", "Narrativa."],
            "6.3": ["6.3 La Simbología Arquetípica y el Autoconocimiento", "Arquetipos."],
            "6.4": ["6.4 Utilizando Metáforas en la Hipnosis y PNL", "Técnica aplicada."],
            "6.5": ["6.5 Ampliando la Creatividad y Resiliencia Mental", "Flexibilidad."],
            "6.6": ["6.6 Las Metáforas en la Práctica Clínica y Terapéutica", "Consultorio."],
            "6.7": ["6.7 Integración de la Metáfora en Vida Cotidiana y Relaciones", "Día a día."],

            "7.0": ["7.0 Enseñanzas Sagradas", "Revelaciones Interiores."],
            "7.1": ["7.1 Comprendiendo Palabras Sagradas de Meishu-Sama", "Johrei y Verdad."],
            "7.2": ["7.2 La Jornada Espiritual a través de Mensajes de Jesucristo", "Amor Crístico."],
            "7.3": ["7.3 Armonizando Saberes Milenarios para la Evolución", "Síntesis."],
            "7.4": ["7.4 La Universalidad de las Enseñanzas Espirituales", "Esencia común."],
            "7.5": ["7.5 La Relevancia de Enseñanzas Sagradas en Era Cuántica", "Actualidad."],
            "7.6": ["7.6 Explorando la Sabiduría Interior por Medio de Enseñanzas", "Gnosis."],
            "7.7": ["7.7 Prácticas Espirituales para el Despertar de la Conciencia", "Acción."],

            "8.0": ["8.0 La Jornada del Autoconocimiento", "Conectando con la Esencia."],
            "8.1": ["8.1 Explorando el Yo Profundo y la Autotransformación", "Inmersión interna."],
            "8.2": ["8.2 En Busca de la Armonía y Equilibrio Interno", "Paz interior."],
            "8.3": ["8.3 Despertando la Conciencia para el Potencial Humano", "Capacidad."],
            "8.4": ["8.4 Herramientas de Autoconocimiento y Autodesarrollo", "Prácticas."],
            "8.5": ["8.5 La Jornada de Cura y Creación de Versión Auténtica", "Autenticidad."],
            "8.6": ["8.6 Integrando la Mente Cuántica al Autoconocimiento", "Gestión de Sí."],
            "8.7": ["8.7 Prácticas Diarias para la Expansión de la Conciencia", "Rutina."],

            "9.0": ["9.0 El Poder de la Mente Subconsciente", "Manifestación."],
            "9.1": ["9.1 La Ciencia de la Manifestación y Ley de Atracción", "Magnetismo."],
            "9.2": ["9.2 La Transformación Por Resignificación de Creencias", "Cambio."],
            "9.3": ["9.3 El Potencial de la Mente Cuántica para Lograr Objetivos", "Foco."],
            "9.4": ["9.4 El Poder del Subconsciente y Realización de Metas", "Logro."],
            "9.5": ["9.5 La Mente Cuántica y la Co-creación de la Realidad", "Creador."],
            "9.6": ["9.6 Prácticas para Fortalecimiento de la Mente Subconsciente", "Entrenamiento."],
            "9.7": ["9.7 Integrando Conciencia Cuántica en Autotransformación", "Fusión."],

            "10.0": ["10.0 Más Allá del Tiempo Lineal", "La Eternidad del Ahora."],
            "10.1": ["10.1 La Conexión con el Eterno Presente", "Power of Now."],
            "10.2": ["10.2 La Dimensión Cuántica del Tiempo y sus Implicaciones", "No-linealidad."],
            "10.3": ["10.3 Viviendo con Mindfulness y Plenitud en el Ahora", "Atención Plena."],
            "10.4": ["10.4 La Mente Cuántica y la Percepción del Tiempo", "Subjetividad."],
            "10.5": ["10.5 Liberando Traumas del Pasado y Preocupaciones Futuras", "Cura temporal."],
            "10.6": ["10.6 La Expansión de la Conciencia en el Flujo del Ahora", "Flow."],
            "10.7": ["10.7 El Presente como Fuente de Transformación y Creación", "Punto Cero."],

            "11.0": ["11.0 Las Claves para la Iluminación", "Amor y Compasión."],
            "11.1": ["11.1 El Amor Incondicional como Fuerza Transformadora", "Ágape."],
            "11.2": ["11.2 La Compasión y la Unidad con la Humanidad", "Empatía."],
            "11.3": ["11.3 El Camino de la Iluminación Por Transformación Interior", "Luz."],
            "11.4": ["11.4 Prácticas Espirituales de Amor y Compasión", "Metta."],
            "11.5": ["11.5 La Conexión entre Amor, Compasión y Conciencia Cuántica", "Frecuencia."],
            "11.6": ["11.6 El Cultivo de la Auto Compasión y Aceptación", "Amor propio."],
            "11.7": ["11.7 La Jornada de Iluminación y Transformación del Ser", "Realización."],

            "12.0": ["12.0 Conexión Entre Mente y Universo", "Explorando Conciencia."],
            "12.1": ["12.1 La Sintonía con la Conciencia Universal", "Resonancia."],
            "12.2": ["12.2 La Intuición y Percepción Más Allá de Cinco Sentidos", "Sexto sentido."],
            "12.3": ["12.3 La Coherencia de Mente Cuántica y Sabiduría Cósmica", "Orden."],
            "12.4": ["12.4 La Conciencia Cósmica y Exploración del Infinito", "Sin límites."],
            "12.5": ["12.5 La Conexión con Inteligencia Universal y Propósito", "Dharma."],
            "12.6": ["12.6 La Conciencia Cósmica en Arte, Ciencia y Espiritualidad", "Expresión."],
            "12.7": ["12.7 Viviendo en Armonía con el Orden Universal", "Tao."],

            "13.0": ["13.0 La Ciencia de la Transformación", "DMT y Psilocibina."],
            "13.1": ["13.1 La Neurociencia Detrás de Experiencias Psicodélicas", "Cerebro."],
            "13.2": ["13.2 El Potencial Terapéutico de Sustancias Psicoactivas", "Medicina."],
            "13.3": ["13.3 La Expansión de Conciencia y Reconexión Interior", "Self."],
            "13.4": ["13.4 La Ciencia del 'Yo' y la Mente en Experiencia Psicodélica", "Disolución del Ego."],
            "13.5": ["13.5 La Transformación Cognitiva y Emocional por Sustancias", "Neuroplasticidad."],
            "13.6": ["13.6 Integrando Experiencias Psicodélicas en Vida Cotidiana", "Aterrizaje."],
            "13.7": ["13.7 Responsabilidad y Orientaciones para Jornada Psicodélica", "Set and Setting."],

            "14.0": ["14.0 El Camino de la Autotransformación", "Espiritualidad."],
            "14.1": ["14.1 Comprendiendo Palabras Sagradas de Meishu-Sama", "Luz Divina."],
            "14.2": ["14.2 Mensajes de Jesucristo y su Interpretación por Kyoshu-Sama", "Mesianismo."],
            "14.3": ["14.3 Armonizando Conocimientos Espirituales para Evolución", "Integración."],
            "14.4": ["14.4 Enseñanzas y Prácticas Espirituales para Autotransformación", "Práctica."],
            "14.5": ["14.5 La Búsqueda por Iluminación y Unificación de Religiones", "Unidad."],

            "15.0": ["15.0 El Arte de la Hipnosis y PNL", "Herramientas de Autoconocimiento."],
            "15.1": ["15.1 La Hipnosis Ericksoniana de Milton Erickson", "Padre de la Hipnosis."],
            "15.2": ["15.2 Técnicas Avanzadas de Hipnosis y PNL de Robert Dilts", "Modelado."],
            "15.3": ["15.3 Utilizando Metáforas en la Hipnosis y PNL", "Lenguaje Indirecto."],
            "15.4": ["15.4 Ampliando la Creatividad y Resiliencia Mental", "Recursos."],
            "15.5": ["15.5 La Comunicación No Verbal y Lenguaje Hipnótico", "Señales."],
            "15.6": ["15.6 Hipnosis y PNL en la Terapia y Transformación", "Clínica."],
            "15.7": ["15.7 Aplicaciones Prácticas para Autodescubrimiento", "Ejercicios."],

            "16.0": ["16.0 Desvelando la Realidad Cuántica", "Más Allá de Límites."],
            "16.1": ["16.1 La Naturaleza Cuántica del Universo y la Mente", "Fundamentos."],
            "16.2": ["16.2 El Papel del Observador y Creación de la Realidad", "Colapso de función."],
            "16.3": ["16.3 Explorando Mente y Conciencia Más Allá de Paradigmas", "Nuevos modelos."],
            "16.4": ["16.4 El Entrelazamiento Cuántico e Interconexión del Todo", "Entrelazamiento."],
            "16.5": ["16.5 La No-Localidad de la Conciencia y de los Fenómenos", "Omnipresencia."],
            "16.6": ["16.6 La Realidad Multidimensional y el Campo Cuántico", "Dimensiones."],
            "16.7": ["16.7 La Ampliación de la Percepción y Nuevos Horizontes", "Evolución."],

            "17.0": ["17.0 La Trascendencia Espiritual", "Elevando la Conciencia."],
            "17.1": ["17.1 La Búsqueda por Conexión Espiritual y Trascendencia", "Lo Sagrado."],
            "17.2": ["17.2 La Unidad con lo Divino y la Esencia Espiritual", "Fusión."],
            "17.3": ["17.3 La Expansión de la Conciencia en Niveles Superiores", "Ascensión."],
            "17.4": ["17.4 El Camino de la Iluminación y Elevación Vibracional", "Energía."],
            "17.5": ["17.5 La Conciencia Cósmica y la Unificación Espiritual", "Todo."],
            "17.6": ["17.6 Prácticas para Trascendencia e Iluminación Interior", "Sadhana."],
            "17.7": ["17.7 El Propósito de Vida y Contribución a la Humanidad", "Misión."],

            "18.0": ["18.0 Más Allá del Ego", "Reconexión Superior."],
            "18.1": ["18.1 La Naturaleza del Ego y sus Desafíos en Jornada Interior", "La máscara."],
            "18.2": ["18.2 El Camino de Desidentificación y Liberación del Ego", "Soltar."],
            "18.3": ["18.3 La Conciencia Superior y el Yo Auténtico", "Self."],
            "18.4": ["18.4 El Despertar de Conciencia Testigo y Presencia Yo Soy", "Observador."],
            "18.5": ["18.5 La Conexión con el Yo Divino y Unidad Esencial", "Chispa."],
            "18.6": ["18.6 La Trascendencia del Ego y Experiencia de la Unidad", "Disolución."],
            "18.7": ["18.7 Integrando la Conciencia Superior en Vida Diaria", "Vivir."],

            "19.0": ["19.0 Ciencia de la Conciencia Cuántica", "Investigaciones."],
            "19.1": ["19.1 Las Fronteras de Neurociencia y Conciencia", "Cerebro-Mente."],
            "19.2": ["19.2 La Resonancia Magnética y Estudios de la Mente", "Imágenes."],
            "19.3": ["19.3 La Epigenética y Influencia del Pensamiento en Salud", "Biología."],
            "19.4": ["19.4 Investigaciones Sobre Mente Cuántica y Estados Ampliados", "Estudios."],
            "19.5": ["19.5 La Conciencia y Expansión de Inteligencia Humana", "Evolución."],
            "19.6": ["19.6 Las Perspectivas Futuras de Ciencia de Conciencia", "Futuro."],
            "19.7": ["19.7 La Interconexión Entre Ciencia y Espiritualidad", "Verdad."],

            "20.0": ["20.0 La Unidad en Portales de Transformación", "Sistémica."],
            "20.1": ["20.1 Herencia de Sabiduría Familiar: Tejiendo Relaciones", "Ancestralidad."],
            "20.2": ["20.2 La Danza de Comunicación: Metáforas e Historias", "Diálogo."],
            "20.3": ["20.3 Alma de Ciencia y Espiritualidad: Diálogo Sagrado", "Encuentro."],
            "20.4": ["20.4 El Ritual de Transformación: Jornada Más Allá del Tiempo", "Rito."],
            "20.5": ["20.5 En Busca de Esencia: El Yo Auténtico y Propósito", "Verdad."],
            "20.6": ["20.6 La Unidad Cósmica: Más Allá del Ego y Mente", "Cosmos."],
            "20.7": ["20.7 El Legado de Virginia Satir: Un Faro para el Futuro", "Familia."],

            "21.1": ["21.1 Recapitulando la Exploración de Portales de Conciencia", "Síntesis."],
            "21.2": ["21.2 El Llamado para Autoconocimiento y Autotransformación", "Acción."],
            "21.3": ["21.3 Un Mensaje de Gratitud a Lectores y Colaboradores", "Gratitud."],
            "21.4": ["21.4 La Percepción Más Allá de Palabras Sagradas", "Esencia."],
            "21.5": ["21.5 Una Invitación a Exploración de Misterios del Ser", "Invitación."],
            "21.6": ["21.6 La Sabiduría Cuántica y Potencial de Transformación", "Potencial."],
            "21.7": ["21.7 El Camino Infinito de Conciencia y Evolución Continua", "Eternidad."]
        }
    }
};

const getSubData = (id: string, lang: Language) => {
    const data = LOCALE_DATA[lang].subchapters[id];
    if (data) return { title: data[0], description: data[1] };
    
    // Fallback to PT
    const ptData = LOCALE_DATA['pt'].subchapters[id];
    if (ptData) return { title: ptData[0], description: ptData[1] };
    
    return { title: `${id} - ${lang.toUpperCase()}`, description: "" };
}

export const getBookStructure = (lang: Language): BookStructure => {
    const locale = LOCALE_DATA[lang];
    
    return {
        title: locale.title,
        subtitle: locale.subtitle,
        chapters: BOOK_SKELETON.map(chap => ({
            id: chap.id,
            title: locale.chapters[chap.id] || chap.id,
            subchapters: chap.subchapters.map(subId => ({
                id: subId,
                ...getSubData(subId, lang)
            }))
        }))
    };
};

export const BOOK_STRUCTURE = getBookStructure('pt');
